name: Build APK with Buildozer

on:
  push:
    branches: [ main ]  # Запускать при пуше в main
  pull_request:
    branches: [ main ]  # Или при PR в main

jobs:
  build:
    runs-on: ubuntu-latest  # Важно: "ubuntu-latest" (нижний регистр)

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"  # Рекомендуемая версия для Kivy

      # Шаг 3: Устанавливаем системные зависимости (исправленный run!)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
           git zip unzip openjdk-17-jdk \
           python3-pip autoconf libtool pkg-config \
           zlib1g-dev libncurses5-dev libncursesw5-dev \
           libtinfo6 cmake libffi-dev libssl-dev  # Изменено на libtinfo6

      # Шаг 4: Устанавливаем Buildozer
      - name: Install Buildozer
        run: pip install buildozer

      # Шаг 5: Собираем APK
      - name: Build APK
        run: |
          buildozer android clean
          buildozer -v android debug

      # Шаг 6: Загружаем APK как артефакт
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mybank-app-debug.apk
          path: bin/*.apk
