name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: |
           sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            libtinfo6 cmake libffi-dev libssl-dev

      - name: Increase SWAP
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Install Buildozer and dependencies
        run: |
          pip install buildozer
          buildozer init

          sudo apt-get install -y unzip openjdk-17-jdk

          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d /usr/lib/android-sdk
          export ANDROID_SDK_ROOT=/usr/lib/android-sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/bin
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
          sdkmanager "ndk;25.1.8937393"
      - name: Build APK
        run: |
         buildozer -v android debug

      - name: Show logs
        run: cat build.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: app-debug.apk
          path: bin/app-debug.apk
