name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

- name: Install system dependencies
  run: |
    sudo apt-get update
    sudo apt-get install -y \
      git zip unzip openjdk-17-jdk \
      python3-pip autoconf libtool pkg-config \
      zlib1g-dev libncurses5-dev libncursesw5-dev \
      libtinfo5 cmake libffi-dev libssl-dev

      - name: Increase SWAP
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Install Buildozer
        run: pip install buildozer

      - name: Build APK
        run: |
          buildozer android clean
          buildozer -v android debug 2>&1 | tee build.log

      - name: Show logs
        run: cat build.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: app-debug.apk
          path: bin/*.apk
